### ISSUE TITLE
webserver.http.port ignored, default port 8090 used instead of 9090

### ISSUE THREAD

**Issue by hamish-spireon** [linkedin/cruise-control#2104]
According to the documentation in cruisecontrol.properties I can set the webserver.http.port configuration to control what port cruise-control starts on.  According to the documentation the default port is 9090. 

However after starting cruise-control it leverages port 8090.  I have a a bunch of services running on port 8080 and I have an nginx inplace to provide access to those services on port 8080.  However since cruise-control does not change its port from 8090 to 8080 this doesn't work.  

I start it using docker:

```
version: "3"
services:
  service-kafka1:
    image: 'bitnami/kafka:3.3'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=INSIDE://0.0.0.0:9091,OUTSIDE://0.0.0.0:29091
      - KAFKA_CFG_ADVERTISED_LISTENERS=INSIDE://service-kafka1:9091,OUTSIDE://__swarm_hostname__:29091
      - KAFKA_CFG_ZOOKEEPER_CONNECT=service-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
    ports:
      - '9091:9091'
      - '29091:29091'
    depends_on:
      - service-zookeeper
  service-kafka2:
    image: 'bitnami/kafka:3.3'
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_LISTENERS=INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INSIDE://service-kafka2:9092,OUTSIDE://__swarm_hostname__:29092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=service-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
    ports:
      - '9092:9092'
      - '29092:29092'
    depends_on:
      - service-zookeeper
  service-zookeeper:
    image: 'bitnami/zookeeper:3.8'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  service-cruisecontrol:
    image: adobe/cruise-control
    volumes:
      - type: bind
        source: ./configs/cruisecontrol.properties
        target: /opt/cruise-control/config/cruisecontrol.properties
    ports:
      - "8912:8080"

```

In my cruisecontrol.properties I have the following line:
`webserver.http.port=8080`

When I start this I can run the following commands:
```
docker exec -it kahu-service-cruisecontrol-1 /bin/bash
apt update
apt install netcat
nc localhost 8080
nc localhost 8090
hello

```
which results in the output:
```
HTTP/1.1 400 No URI
Content-Type: text/html;charset=iso-8859-1
Content-Length: 49
Connection: close
Server: Jetty(9.4.53.v20231009)

<h1>Bad Message 400</h1><pre>reason: No URI</pre>
```

Clearly cruise control is not using the port configured
