### ISSUE TITLE
Are user-provided goals in kafkarebalance spec treated as hard goals?

### ISSUE THREAD

**Issue by sreelu27** [linkedin/cruise-control#2117]
Scenario: is below goals treated as hard goals

```
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaRebalance
metadata:
  name: my-rebalance
  labels:
    strimzi.io/cluster: my-cluster
spec:
  goals:
    - NetworkInboundCapacityGoal
    - DiskCapacityGoal
    - RackAwareGoal
    - NetworkOutboundCapacityGoal
    - CpuCapacityGoal
    - ReplicaCapacityGoal 
```
